.PHONY:

# 4.2.03 mandrill
# 4.2.04 lena (removed from SIPI)
# 4.2.07 peppers

fix-last-modified:
	touch -t 199707110000 lena.tiff
	touch -t 199707110000 lena.jpg
	touch -t 201108160000 tiger.svg

download-samples:
	wget -c https://sipi.usc.edu/database/misc.tar.gz
